// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.GameUi = (function(_super) {
    __extends(GameUi, _super);

    function GameUi(_opts) {
      this._keyDown = __bind(this._keyDown, this);
      var _this = this;
      this.options = _opts || {};
      $(window).on('keydown', this._keyDown).mousemove(this._mouseMove);
      this.hammer = Hammer(document);
      this.hammer.on('swipeleft', function(e) {
        return _this.trigger('answer-yes', e);
      });
      this.hammer.on('swiperight', function(e) {
        return _this.trigger('answer-no', e);
      });
    }

    GameUi.prototype._keyDown = function(e) {
      if (e.metaKey || e.ctrlKey) {
        return;
      }
      e.preventDefault();
      if (e.keyCode === 78) {
        this.trigger('answer-no', e);
      }
      if (e.keyCode === 89) {
        this.trigger('answer-yes', e);
      }
      if (e.keyCode === 37) {
        this.trigger('answer-yes', e);
      }
      if (e.keyCode === 39) {
        this.trigger('answer-no', e);
      }
      if (e.keyCode === 9) {
        return this.trigger('toggle-stats', e);
      }
    };

    return GameUi;

  })(Backbone.Model);

}).call(this);
